
Couldn't find a valid proxy.

Preprocessing:   0%|          | 0/10 [00:00<?, ?file/s]Preprocessing:   0%|          | 0/10 [00:12<?, ?file/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-f74f0/x86_64-centos7-gcc8-opt/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 990, in automatic_retries
    raise e
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 978, in automatic_retries
    return func(*args, **kwargs)
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 1041, in metadata_fetcher
    file = uproot.open(item.filename, timeout=xrootdtimeout)
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/reading.py", line 154, in open
    **options  # NOTE: a comma after **options breaks Python 2
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/reading.py", line 590, in __init__
    file_path, **self._options  # NOTE: a comma after **options breaks Python 2
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/source/xrootd.py", line 273, in __init__
    self._open()
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/source/xrootd.py", line 276, in _open
    self._resource = XRootDResource(self._file_path, self._timeout)
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/source/xrootd.py", line 84, in __init__
    self._open()
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/source/xrootd.py", line 93, in _open
    self._xrd_error(status)
  File "/var/lib/condor/execute/dir_84606/site-packages/uproot/source/xrootd.py", line 116, in _xrd_error
    raise uproot._util._file_not_found(self._file_path, status.message)
FileNotFoundError: file not found ([ERROR] Server responded with an error: [3022] invalid argument
)

    'root://xrootd-cms.infn.it//store/mc/RunIISummer20UL17NanoAODv9/QCD_HT1000to1500_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/80000/511C73D3-2B6A-4543-842B-2808B7820DC8.root'

Files may be specified as:
   * str/bytes: relative or absolute filesystem path or URL, without any colons
         other than Windows drive letter or URL schema.
         Examples: "rel/file.root", "C:\abs\file.root", "http://where/what.root"
   * str/bytes: same with an object-within-ROOT path, separated by a colon.
         Example: "rel/file.root:tdirectory/ttree"
   * pathlib.Path: always interpreted as a filesystem path or URL only (no
         object-within-ROOT path), regardless of whether there are any colons.
         Examples: Path("rel:/file.root"), Path("/abs/path:stuff.root")

Functions that accept many files (uproot.iterate, etc.) also allow:
   * glob syntax in str/bytes and pathlib.Path.
         Examples: Path("rel/*.root"), "/abs/*.root:tdirectory/ttree"
   * dict: keys are filesystem paths, values are objects-within-ROOT paths.
         Example: {"/data_v1/*.root": "ttree_v1", "/data_v2/*.root": "ttree_v2"}
   * already-open TTree objects.
   * iterables of the above.

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 51, in <module>
    executor_args={'schema': NanoAODSchema,'workers':  options.workers},
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/__init__.py", line 107, in _run_x_job
    processor_instance=processor_instance,
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 1296, in __call__
    self._preprocess_fileset(fileset)
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 1081, in _preprocess_fileset
    out = pre_executor(to_get, closure, out)
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 579, in __call__
    return processwith(pool=poolinstance)
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 569, in processwith
    accumulator,
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/accumulator.py", line 94, in accumulate
    accum = iadd(accum, next(gen))
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/accumulator.py", line 86, in <genexpr>
    gen = (x for x in items if x is not None)
  File "/var/lib/condor/execute/dir_84606/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/var/lib/condor/execute/dir_84606/site-packages/coffea/processor/executor.py", line 240, in _futures_handler
    yield done.pop().result()
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-f74f0/x86_64-centos7-gcc8-opt/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-f74f0/x86_64-centos7-gcc8-opt/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: file not found ([ERROR] Server responded with an error: [3022] invalid argument
)

    'root://xrootd-cms.infn.it//store/mc/RunIISummer20UL17NanoAODv9/QCD_HT1000to1500_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/80000/511C73D3-2B6A-4543-842B-2808B7820DC8.root'

Files may be specified as:
   * str/bytes: relative or absolute filesystem path or URL, without any colons
         other than Windows drive letter or URL schema.
         Examples: "rel/file.root", "C:\abs\file.root", "http://where/what.root"
   * str/bytes: same with an object-within-ROOT path, separated by a colon.
         Example: "rel/file.root:tdirectory/ttree"
   * pathlib.Path: always interpreted as a filesystem path or URL only (no
         object-within-ROOT path), regardless of whether there are any colons.
         Examples: Path("rel:/file.root"), Path("/abs/path:stuff.root")

Functions that accept many files (uproot.iterate, etc.) also allow:
   * glob syntax in str/bytes and pathlib.Path.
         Examples: Path("rel/*.root"), "/abs/*.root:tdirectory/ttree"
   * dict: keys are filesystem paths, values are objects-within-ROOT paths.
         Example: {"/data_v1/*.root": "ttree_v1", "/data_v2/*.root": "ttree_v2"}
   * already-open TTree objects.
   * iterables of the above.

ls: cannot access hists/UL_BFF_v1_test_v3_2017/QCD_HT1000to1500_TuneCP5_PSWeights_13TeV-madgraph-pythia8____1_.futures: No such file or directory
cp: cannot stat 'hists/UL_BFF_v1_test_v3_2017/QCD_HT1000to1500_TuneCP5_PSWeights_13TeV-madgraph-pythia8____1_.futures': No such file or directory
